[package]
name = "liveboat"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"

libnewsboat = { path="./sub/newsboat/rust/libnewsboat" }
rusqlite = "0.32.1"
serde_json = "1.0.133"

[[bin]]
name = "liveboat"
path = "src/main.rs"
