[package]
name = "liveboat"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
serde = { version = "1.0.215", features = ["derive"] }

libnewsboat = { path="./sub/newsboat/rust/libnewsboat" }

toml = "0.8.19"
rusqlite = "0.32.1"
serde_json = "1.0.133"
chrono = "0.4.38"
bs58 = "0.5.1"
handlebars = "6.2.0"
rand = "0.8.5"

[[bin]]
name = "liveboat"
path = "src/main.rs"
