name: liveboat
version: 1.1.5
summary: Static page generator and aggregator for RSS feeds
description: |
  Liveboat is a static page generator which uses Newsboat RSS reader feed data and turns it into beautiful static websites.

base: core24
adopt-info: liveboat
grade: stable
confinement: strict

plugs:
  allow-access-to-newsboat-files:
    interface: personal-files
    read:
      - $HOME/.newsboat
      - $HOME/snap/newsboat/current/.newsboat

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

apps:
  liveboat:
    command: bin/liveboat
    plugs:
      - home
      - network
      - desktop
      - allow-access-to-newsboat-files

parts:
  liveboat:
    plugin: rust
    source: .
