name = "Default Template"
version = "1.0.6"
author = "Konrad Wasowicz (exaroth@gmail.com)"

[template_settings]
text-color = "#c7cfcc"
highlight-color = "#73bed3"
accent-color = "#2D4566"
background-color = "#121414"
