name = "Default Template"
builder = "spa"
version = "1.2.3"
author = "Konrad Wasowicz (exaroth@gmail.com)"

[template_settings]
text-color = "#c7cfcc"
highlight-color = "#73bed3"
accent-color = "#2D4566"
background-color = "#121414"
custom-color = "#f3a833"
autoreload = "1"
header-svg = "/assets/rocket.svg"
