name: ghcr build

on:
  workflow_dispatch:

jobs:
  template-builder:
    name: Build and push docker images
    runs-on: ubuntu-latest
    steps:
      - name: Print triggering branch
        run: echo ${{ github.event.client_payload.ref }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: refs/heads/develop

      - name: Set env
        run: echo "RELEASE=$(cat VERSION | tr -d '[:space:]')" >> $GITHUB_ENV

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/liveboat

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug
        run: |
          echo ${{ steps.meta.outputs.tags }}
          echo ${{ steps.meta.outputs.labels }}
          echo ${{ env.RELEASE }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
