name: template-builder
on:
  repository_dispatch:
    types: [dispatch-templates]

jobs:
  template-builder:
    name: Deploy templates
    runs-on: ubuntu-latest
    steps:
      - name: Print triggering branch
        run: echo ${{ github.event.client_payload.ref }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Compile templates
        run:
          make bundle-templates

      - name: Upload templates for nightly
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./tmp/templates.tar.gz
          asset_name: templates.tar.gz
          tag: nightly
          overwrite: true
        if: |
          github.event.client_payload.ref == 'refs/heads/develop' ||
          startsWith(github.event.client_payload.ref, 'refs/heads/feature/') ||
          startsWith(github.event.client_payload.ref, 'refs/heads/release/')

      - name: Upload templates for tag
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./tmp/templates.tar.gz
          asset_name: templates.tar.gz
          tag: ${{ github.event.client_payload.ref }}
        if: startsWith(github.event.client_payload.ref, 'refs/tags/')

      - name: Upload templates for release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./tmp/templates.tar.gz
          asset_name: templates.tar.gz
          tag: stable
          overwrite: true
        if: github.event.client_payload.ref == 'refs/heads/main'
