name: aux-deployer
on:
  repository_dispatch:
    types: [dispatch-crumbs]

jobs:
  template-builder:
    name: Deploy auxiliary data
    runs-on: ubuntu-latest
    steps:
      - name: Print triggering branch
        run: echo ${{ github.event.client_payload.ref }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Upload VERSION file for release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./VERSION
          asset_name: VERSION
          tag: stable
          overwrite: true
        if: github.event.client_payload.ref == 'refs/heads/main'
      - name: Upload VERSION file for nightly
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./VERSION
          asset_name: VERSION
          tag: nightly
          overwrite: true
        if: github.event.client_payload.ref == 'refs/heads/develop'
