name: template-builder

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - cross-compile
    types:
      - completed
    branches: ["v*.*.*", "main", "develop", "release/*", "feature/*"]

jobs:
  template-builder:
    name: Deploy templates
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Compile templates
        run:
          make bundle-templates
      - name: Upload templates for nightly
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./tmp/templates.tar.gz
          asset_name: templates.tar.gz
          tag: nightly
          overwrite: true
        if: |
          github.event.workflow_run.head_branch == 'develop' ||
          startsWith(github.event.workflow_run.head_branch, 'feature/') ||
          startsWith(github.event.workflow_run.head_branch, 'release/')
      - name: Upload templates for tag
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./tmp/templates.tar.gz
          asset_name: templates.tar.gz
          tag: ${{ github.event.workflow_run.head_branch }}
        if: startsWith(github.event.workflow_run.head_branch, 'v')
      - name: Upload templates for release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./tmp/templates.tar.gz
          asset_name: templates.tar.gz
          tag: stable
          overwrite: true
        if: github.event.workflow_run.head_branch == 'main'
